# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-23 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_auto_20181121_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='clock_out',
            field=models.DateTimeField(null=True),
        ),
    ]
