# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-23 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_auto_20181123_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='report',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day', to='timesheets.Report'),
        ),
    ]
