# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-24 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_auto_20181124_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='report',
        ),
        migrations.AddField(
            model_name='report',
            name='day',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='timesheets.Day'),
        ),
    ]
