# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-24 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0006_auto_20181124_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
